from enum import Enum


class Command(Enum):
    STOP = "STOP"
    MOVE_RIGHT = "MOVE_RIGHT"
    MOVE_LEFT = "MOVE_LEFT"
    MOVE_FORWARD = "MOVE_FORWARD"
    MOVE_BACKWARD = "MOVE_BACKWARD"
    ROTATE_RIGHT = "ROTATE_RIGHT"
    ROTATE_LEFT = "ROTATE_LEFT"
